apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: dummy-react-app
spec:
  selector:
    app: react-app
  ports:
    - port: 8080
      targetPort: 80
      
  type: LoadBalancer